version: '2'
services:
  antimalware:
          image: antim
          ports:
             - 80:80
             - 443:443 
          volumes:
             - ./webui:/var/www/html
             - ./antim:/antim
             - ./antim/clamav/conf:/etc/clamav
        #    - ./antim/apache2:/etc/apache2 servie can't restart. PID conflitcs
          environment:
             - SET_CONTAINER_TIMEZONE=true
             - CONTAINER_TIMEZONE=Asia/Tokyo
