version: '2'
services:
  antimalware:
          image: antim_2
          ports:
             - 80:80
             - 443:443 
          volumes:
             - ./webui:/var/www/html
             - ./antim:/antim
             - ./antim/clamav/conf:/etc/clamav
             - ./apache2:/etc/apache2
          environment:
             - SET_CONTAINER_TIMEZONE=true
             - CONTAINER_TIMEZONE=Asia/Tokyo
